-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db/drop_event_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__notifications_event AS
SELECT
  ne_id,
  ne_key,
  ne_agent,
  ne_timestamp,
  ne_payload,
  ne_process,
  ne_process_result
FROM /*_*/notifications_event;
DROP TABLE /*_*/notifications_event;


CREATE TABLE /*_*/notifications_event (
    ne_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ne_key BLOB DEFAULT NULL, ne_agent INTEGER NOT NULL,
    ne_timestamp BLOB DEFAULT NULL, ne_payload BLOB NOT NULL,
    ne_process BLOB DEFAULT NULL, ne_process_result BLOB DEFAULT ''
  );
INSERT INTO /*_*/notifications_event (
    ne_id, ne_key, ne_agent, ne_timestamp,
    ne_payload, ne_process, ne_process_result
  )
SELECT
  ne_id,
  ne_key,
  ne_agent,
  ne_timestamp,
  ne_payload,
  ne_process,
  ne_process_result
FROM
  /*_*/__temp__notifications_event;
DROP TABLE /*_*/__temp__notifications_event;
