-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/NotifyMe/db/notifications_instance_patch_wiki_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__notifications_instance AS
SELECT
  ni_id,
  ni_event_type,
  ni_event_id,
  ni_target_user,
  ni_channel,
  ni_status,
  ni_payload
FROM /*_*/notifications_instance;
DROP TABLE /*_*/notifications_instance;


CREATE TABLE /*_*/notifications_instance (
    ni_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ni_event_type BLOB NOT NULL, ni_event_id BLOB NOT NULL,
    ni_target_user INTEGER NOT NULL, ni_channel BLOB NOT NULL,
    ni_status BLOB NOT NULL, ni_payload BLOB NOT NULL,
    ni_wiki_id BLOB DEFAULT NULL
  );
INSERT INTO /*_*/notifications_instance (
    ni_id, ni_event_type, ni_event_id,
    ni_target_user, ni_channel, ni_status,
    ni_payload
  )
SELECT
  ni_id,
  ni_event_type,
  ni_event_id,
  ni_target_user,
  ni_channel,
  ni_status,
  ni_payload
FROM
  /*_*/__temp__notifications_instance;
DROP TABLE /*_*/__temp__notifications_instance;

CREATE UNIQUE INDEX notifications_instance_event_channel_target ON /*_*/notifications_instance (
    ni_event_id, ni_channel, ni_target_user,
    ni_wiki_id
  );
