-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_web_query_store.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/notifications_web_query_store (
  nwqs_notification_id INTEGER UNSIGNED NOT NULL,
  nwqs_status BLOB NOT NULL,
  nwqs_target_user INTEGER UNSIGNED NOT NULL,
  nwqs_notification_timestamp BLOB NOT NULL,
  nwqs_namespace_id INTEGER DEFAULT NULL,
  nwqs_namespace_text BLOB DEFAULT NULL,
  nwqs_title BLOB DEFAULT NULL,
  nwqs_categories CLOB DEFAULT NULL,
  nwqs_buckets CLOB DEFAULT NULL,
  PRIMARY KEY(nwqs_notification_id)
);
