-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/NotifyMe/db/notifications_web_query_store_patch_wiki_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__notifications_web_query_store AS
SELECT
  nwqs_notification_id,
  nwqs_status,
  nwqs_target_user,
  nwqs_notification_timestamp,
  nwqs_namespace_id,
  nwqs_namespace_text,
  nwqs_title,
  nwqs_categories,
  nwqs_buckets
FROM /*_*/notifications_web_query_store;
DROP TABLE /*_*/notifications_web_query_store;


CREATE TABLE /*_*/notifications_web_query_store (
    nwqs_notification_id INTEGER UNSIGNED NOT NULL,
    nwqs_wiki_id BLOB NOT NULL,
    nwqs_status BLOB NOT NULL,
    nwqs_target_user INTEGER UNSIGNED NOT NULL,
    nwqs_notification_timestamp BLOB NOT NULL,
    nwqs_namespace_id INTEGER DEFAULT NULL,
    nwqs_namespace_text BLOB DEFAULT NULL,
    nwqs_title BLOB DEFAULT NULL,
    nwqs_categories CLOB DEFAULT NULL,
    nwqs_buckets CLOB DEFAULT NULL,
    PRIMARY KEY(
      nwqs_notification_id, nwqs_wiki_id
    )
  );
INSERT INTO /*_*/notifications_web_query_store (
    nwqs_notification_id, nwqs_status,
    nwqs_target_user, nwqs_notification_timestamp,
    nwqs_namespace_id, nwqs_namespace_text,
    nwqs_title, nwqs_categories, nwqs_buckets
  )
SELECT
  nwqs_notification_id,
  nwqs_status,
  nwqs_target_user,
  nwqs_notification_timestamp,
  nwqs_namespace_id,
  nwqs_namespace_text,
  nwqs_title,
  nwqs_categories,
  nwqs_buckets
FROM
  /*_*/__temp__notifications_web_query_store;
DROP TABLE /*_*/__temp__notifications_web_query_store;
