-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_instance.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/notifications_instance (
  ni_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ni_event_type BLOB NOT NULL, ni_event_id BLOB NOT NULL,
  ni_target_user INTEGER NOT NULL, ni_channel BLOB NOT NULL,
  ni_status BLOB NOT NULL, ni_payload BLOB NOT NULL
);

CREATE UNIQUE INDEX notifications_instance_event_channel_target ON /*_*/notifications_instance (
  ni_event_id, ni_channel, ni_target_user
);
