-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_event.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/notifications_event (
  ne_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ne_key BLOB DEFAULT NULL, ne_agent INTEGER NOT NULL,
  ne_timestamp BLOB DEFAULT NULL, ne_payload BLOB NOT NULL,
  ne_process BLOB DEFAULT NULL, ne_process_result BLOB DEFAULT ''
);
