-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_web_query_store.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/notifications_web_query_store (
  nwqs_notification_id INT UNSIGNED NOT NULL,
  nwqs_status VARBINARY(255) NOT NULL,
  nwqs_target_user INT UNSIGNED NOT NULL,
  nwqs_notification_timestamp BINARY(14) NOT NULL,
  nwqs_namespace_id INT DEFAULT NULL,
  nwqs_namespace_text VARBINARY(255) DEFAULT NULL,
  nwqs_title VARBINARY(255) DEFAULT NULL,
  nwqs_categories LONGTEXT DEFAULT NULL,
  nwqs_buckets LONGTEXT DEFAULT NULL,
  PRIMARY KEY(nwqs_notification_id)
) /*$wgDBTableOptions*/;
