-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_instance.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/notifications_instance (
  ni_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  ni_event_type VARBINARY(255) NOT NULL,
  ni_event_id VARBINARY(255) NOT NULL,
  ni_target_user INT NOT NULL,
  ni_channel VARBINARY(255) NOT NULL,
  ni_status VARBINARY(255) NOT NULL,
  ni_payload LONGBLOB NOT NULL,
  UNIQUE INDEX notifications_instance_event_channel_target (
    ni_event_id, ni_channel, ni_target_user
  ),
  PRIMARY KEY(ni_id)
) /*$wgDBTableOptions*/;
