-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_event.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/notifications_event (
  ne_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  ne_key VARBINARY(255) DEFAULT NULL,
  ne_agent INT NOT NULL,
  ne_timestamp BINARY(14) DEFAULT NULL,
  ne_payload LONGBLOB NOT NULL,
  ne_process VARBINARY(128) DEFAULT NULL,
  ne_process_result VARBINARY(10) DEFAULT '',
  PRIMARY KEY(ne_id)
) /*$wgDBTableOptions*/;
