-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/NotifyMe/db/notifications_web_query_store_patch_wiki_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX `primary` ON /*_*/notifications_web_query_store;
ALTER TABLE /*_*/notifications_web_query_store
  ADD nwqs_wiki_id VARBINARY(255) NOT NULL;
ALTER TABLE /*_*/notifications_web_query_store
  ADD PRIMARY KEY (
    nwqs_notification_id, nwqs_wiki_id
  );
