-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/NotifyMe/db/notifications_instance_patch_wiki_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX notifications_instance_event_channel_target ON /*_*/notifications_instance;
ALTER TABLE /*_*/notifications_instance
  ADD ni_wiki_id VARBINARY(255) DEFAULT NULL;

CREATE UNIQUE INDEX notifications_instance_event_channel_target ON /*_*/notifications_instance (
    ni_event_id, ni_channel, ni_target_user,
    ni_wiki_id
  );
