-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db/drop_event_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX notifications_event_key_timestamp;
