-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_instance.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE notifications_instance (
  ni_id SERIAL NOT NULL,
  ni_event_type TEXT NOT NULL,
  ni_event_id TEXT NOT NULL,
  ni_target_user INT NOT NULL,
  ni_channel TEXT NOT NULL,
  ni_status TEXT NOT NULL,
  ni_payload TEXT NOT NULL,
  PRIMARY KEY(ni_id)
);

CREATE UNIQUE INDEX notifications_instance_event_channel_target ON notifications_instance (
  ni_event_id, ni_channel, ni_target_user
);
