-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/NotifyMe/db/notifications_web_query_store_patch_wiki_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE notifications_web_query_store
  DROP CONSTRAINT notifications_web_query_store_pkey;
ALTER TABLE notifications_web_query_store
  ADD nwqs_wiki_id TEXT NOT NULL;
ALTER TABLE notifications_web_query_store
  ADD PRIMARY KEY (
  nwqs_notification_id, nwqs_wiki_id
);
