-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_event.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE notifications_event (
  ne_id SERIAL NOT NULL,
  ne_key TEXT DEFAULT NULL,
  ne_agent INT NOT NULL,
  ne_timestamp TIMESTAMPTZ DEFAULT NULL,
  ne_payload TEXT NOT NULL,
  ne_process TEXT DEFAULT NULL,
  ne_process_result TEXT DEFAULT '',
  PRIMARY KEY(ne_id)
);
