-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/notifications_web_query_store.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE notifications_web_query_store (
  nwqs_notification_id INT NOT NULL,
  nwqs_status TEXT NOT NULL,
  nwqs_target_user INT NOT NULL,
  nwqs_notification_timestamp TIMESTAMPTZ NOT NULL,
  nwqs_namespace_id INT DEFAULT NULL,
  nwqs_namespace_text TEXT DEFAULT NULL,
  nwqs_title TEXT DEFAULT NULL,
  nwqs_categories TEXT DEFAULT NULL,
  nwqs_buckets TEXT DEFAULT NULL,
  PRIMARY KEY(nwqs_notification_id)
);
